export const menuItemsData = [
  {
    id: 1,
    name: 'Fresh Curry Leaves - 20g',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 149,
    img: '/images/Curry_Leaves.jpg',
  },
  {
    id: 2,
    name: 'Fresh Green Chillies - 300g',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 299,
    img: '/images/GreenChillies.jpg',
  },
  {
    id: 3,
    name: 'Fresh Karela - 300g',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 299,
    img: '/images/Karela.jpg',
  },
  {
    id: 4,
    name: 'Fresh Raw Mango - 1 pc',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 299,
    img: '/images/Fresh_Raw_Mango.jpg',
  },
  {
    id: 5,
    name: 'Fresh Okra - 300g',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 299,
    img: '/images/Okra.jpg',
  },
  {
    id: 6,
    name: 'Moong Dal Yellow - 500g',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 199,
    img: '/images/Top-Op_Moong_Dal_Yellow.jpg',
  },
  {
    id: 7,
    name: 'Toor Dal Plain - 1kg',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 149,
    img: '/images/Top-Op_Toor_Dal_Plain.jpg',
  },
  {
    id: 8,
    name: 'Soya Wadi Chunks - 700g',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 169,
    img: '/images/Top-Op_Soya_Chunks.jpg',
  },
  {
    id: 9,
    name: 'Vermicelli - 500g',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 149,
    img: '/images/Purvi_Vermiceli_Cut_Broken_220x.jpg',
  },
  {
    id: 10,
    name: 'Moong Dal Split - 500g',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 199,
    img: '/images/Top-Op_Moong_Dal_Split_500g_220x.jpg',
  },
  {
    id: 11,
    name: 'Pure Mustard Oil - 250ml',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 149,
    img: '/images/Niharti_Mustard_Oil_250ml_180x.jpg',
  },
  {
    id: 12,
    name: 'Pure Sesame Oil - 250ml',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 199,
    img: '/images/Niharti_Sesame_Oil_250ml_180x.jpg',
  },
  {
    id: 13,
    name: 'Pure Almond Oil - 1 Ltr',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 199,
    img: '/images/Niharti_Almond_Oil_1ltr_180x.jpg',
  },
  {
    id: 14,
    name: 'Virgin Black Seed Oil - 50ml',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 499,
    img: '/images/Niharti_Black_Seed_Oil_Kaloonji_Oil_50ml_180x.jpg',
  },
  {
    id: 15,
    name: 'Extra Virgin Olive Oil - 250ml',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 299,
    img: '/images/Niharti_Extra_Virgin_Olive_Oil_250ml_180x.jpg',
  },
  {
    id: 16,
    name: 'Mango Pickle - 283g',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 239,
    img: '/images/Patak_s_Mango_Pickle_283g_180x.jpg',
  },
  {
    id: 17,
    name: 'Lime Pickle - 310g',
    info: 'For making your dishes more scrumptious and enjoyable',
    price: 124,
    img: '/images/Niharti_Lime_Pickle_180x.jpg',
  },
];
